services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: enfi7625
      MYSQL_DATABASE: tablas
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


      