services:
  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "80:80"  # Exponer el puerto 80 para Nginx
    depends_on:
      - mariadb

volumes:
  mariadb_data: