# version: '3.8'


services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app  # Monta el directorio de la aplicación
    environment:
    - FLASK_ENV=development  
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: indicadores
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data: